name: BudiDD
channels:
  - defaults
dependencies:
  - numpy
  - matplotlib
  - pandas
  - xlrd
  - openpyxl
  - lxml
  - jupyter
  - plotly
  - seaborn
  - geopandas
  - networkx
  - descartes
  - scipy
  - pip
  - pip:
    - cyrtranslit

